// ─── MCP Config Writer (v8.20.0 — Zero-Config UX) ──────────────────────────
// File-level operations on .fluxo/mcp_servers.json. Single source of truth
// for both the boot-time auto-inject path (mcpClient.ts) and the user-facing
// CLI / VSCode commands (commands/mcp.ts, extension.ts). All ops are
// idempotent: re-running ensureStarterPack on a populated workspace is a
// no-op, addServer on an existing alias is a no-op, removeServer on a
// missing alias is a no-op.

import * as fs from 'fs';
import * as path from 'path';
import { OFFICIAL_REGISTRY, RegistryEntry, getStarterPack, getRegistryEntry } from './mcpRegistry';

const CONFIG_RELATIVE = path.join('.fluxo', 'mcp_servers.json');

export interface ServerEntry {
  command: string;
  args?: string[];
  env?: Record<string, string>;
  categories?: string[];
}

export interface ConfigShape {
  /** Header note rendered for humans editing the file by hand. */
  _comment?: string;
  /** When the registry generates a per-server note, it lands here keyed by alias. */
  _notes?: Record<string, string>;
  /** Active servers. Keys are aliases, values are the StdioClientTransport-compatible config. */
  mcpServers: Record<string, ServerEntry>;
}

function configPath(workspacePath: string): string {
  return path.join(workspacePath, CONFIG_RELATIVE);
}

function ensureDir(workspacePath: string): void {
  fs.mkdirSync(path.join(workspacePath, '.fluxo'), { recursive: true });
}

/**
 * Load the existing config or return an empty shape. Tolerant of legacy
 * formats: a root-level map { server: {...} } is auto-promoted to the
 * envelope { mcpServers: { server: {...} } } before being returned.
 */
export function readConfig(workspacePath: string): ConfigShape {
  const fp = configPath(workspacePath);
  if (!fs.existsSync(fp)) {
    return { mcpServers: {} };
  }
  try {
    const parsed = JSON.parse(fs.readFileSync(fp, 'utf-8'));
    if (!parsed || typeof parsed !== 'object') {
      return { mcpServers: {} };
    }
    if (parsed.mcpServers && typeof parsed.mcpServers === 'object') {
      return parsed as ConfigShape;
    }
    // Legacy root-level map — promote to envelope.
    return { mcpServers: parsed as Record<string, ServerEntry> };
  } catch {
    // Corrupt JSON — return empty so callers can re-seed without losing
    // their workspace setup. The original file is left intact on disk for
    // the user to fix manually.
    return { mcpServers: {} };
  }
}

function writeConfig(workspacePath: string, cfg: ConfigShape): void {
  ensureDir(workspacePath);
  cfg._comment = cfg._comment ?? 'Generated by Fluxo AI v8.20.0. Edit by hand or use `Fluxo: Add MCP Server` from the command palette / `node out/commands/mcp.js add <alias>` from the CLI.';
  fs.writeFileSync(configPath(workspacePath), JSON.stringify(cfg, null, 2) + '\n', 'utf-8');
}

function entryToServer(entry: RegistryEntry): ServerEntry {
  const server: ServerEntry = {
    command: entry.command,
    args: entry.args ? [...entry.args] : undefined,
    categories: entry.categories ? [...entry.categories] : undefined,
  };
  if (entry.env) {
    server.env = { ...entry.env };
  }
  return server;
}

// ─── Public API ─────────────────────────────────────────────────────────────

/**
 * On first boot in a workspace that has never configured MCP, this drops a
 * starter pack JSON onto disk so the agent has something useful immediately
 * — no docs, no manual editing. Returns the list of aliases that were
 * actually written. If the file already exists, this is a no-op and returns
 * an empty array (we never overwrite user choices).
 */
export function ensureStarterPack(workspacePath: string): string[] {
  if (!workspacePath) { return []; }
  const fp = configPath(workspacePath);
  if (fs.existsSync(fp)) { return []; }

  const starters = getStarterPack();
  if (starters.length === 0) { return []; }

  const cfg: ConfigShape = { mcpServers: {}, _notes: {} };
  for (const entry of starters) {
    cfg.mcpServers[entry.alias] = entryToServer(entry);
    if (entry.note && cfg._notes) { cfg._notes[entry.alias] = entry.note; }
  }
  writeConfig(workspacePath, cfg);
  return starters.map(e => e.alias);
}

export interface AddResult {
  ok: boolean;
  alias: string;
  reason?: string;
}

/** Add a registry entry to the workspace config. Idempotent. */
export function addServer(workspacePath: string, alias: string): AddResult {
  if (!workspacePath) { return { ok: false, alias, reason: 'No workspace path provided.' }; }
  const entry = getRegistryEntry(alias);
  if (!entry) {
    const known = Object.keys(OFFICIAL_REGISTRY).sort().join(', ');
    return { ok: false, alias, reason: `Unknown server "${alias}". Known aliases: ${known}.` };
  }
  const cfg = readConfig(workspacePath);
  if (cfg.mcpServers[entry.alias]) {
    return { ok: true, alias: entry.alias, reason: `"${entry.alias}" is already configured. No changes written.` };
  }
  cfg.mcpServers[entry.alias] = entryToServer(entry);
  if (entry.note) {
    cfg._notes = { ...(cfg._notes ?? {}), [entry.alias]: entry.note };
  }
  writeConfig(workspacePath, cfg);
  return { ok: true, alias: entry.alias };
}

/** Remove a server from the workspace config. Idempotent. */
export function removeServer(workspacePath: string, alias: string): AddResult {
  if (!workspacePath) { return { ok: false, alias, reason: 'No workspace path provided.' }; }
  const cfg = readConfig(workspacePath);
  if (!cfg.mcpServers[alias]) {
    return { ok: true, alias, reason: `"${alias}" was not configured. No changes written.` };
  }
  delete cfg.mcpServers[alias];
  if (cfg._notes) { delete cfg._notes[alias]; }
  writeConfig(workspacePath, cfg);
  return { ok: true, alias };
}

export function listConfigured(workspacePath: string): Record<string, ServerEntry> {
  return readConfig(workspacePath).mcpServers;
}
