name: Build and Release VSIX

on:
  push:
    tags:
      - 'v*'

# Damos permiso explícito para crear Releases
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Forzamos Node 24 para apagar el warning del año 2026
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build VSIX
        run: |
          npm install -g @vscode/vsce
          vsce package
        
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: '*.vsix'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}